services:
  backend:
    build:
      context: .
      dockerfile: my-blog-backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - static_data:/app/static
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ADMIN_SECRET_KEY=${ADMIN_SECRET_KEY}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SENDER_AUTH_CODE=${SENDER_AUTH_CODE}
      - ENV=development   # 到时候记得改回来！！！！！！！！！
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: my-blog-frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
  static_data: