import requests
import os
from datetime import datetime, timedelta, timezone
import asyncio
from dotenv import load_dotenv
load_dotenv()

TZ_BEIJING = timezone(timedelta(hours=8))
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY", "")
DEEPSEEK_BASE_URL = "https://api.deepseek.com/v1"

def fetch_github_trending():
    """获取过去 1 天内创建的最热门 3 个仓库"""
    one_day_ago = (datetime.now(TZ_BEIJING) - timedelta(days=1)).strftime("%Y-%m-%d")
    url = "https://api.github.com/search/repositories"
    params = {
        "q": f"stars:>50 created:>{one_day_ago}",
        "sort": "stars",
        "order": "desc",
        "per_page": 3
    }
    headers = {"Accept": "application/vnd.github.v3+json"}
    try:
        resp = requests.get(url, headers=headers, params=params, timeout=10)
        if resp.status_code == 200:
            return resp.json().get("items", [])
        else:
            print(f"GitHub API error: {resp.status_code}")
            return []
    except Exception as e:
        print(f"Failed to fetch trending: {e}")
        return []

def generate_trending_summary(repos):
    """用英文生成简短有趣的趋势总结"""
    if not repos:
        return "No notable repositories in the last 24 hours."

    repo_lines = []
    for r in repos:
        name = r["full_name"]
        desc = r.get("description") or "No description"
        stars = r["stargazers_count"]
        language = r.get("language") or "N/A"
        topics = r.get("topics", [])
        topics_str = ", ".join(topics[:3]) if topics else "none"
        forks = r.get("forks_count", 0)
        url = r["html_url"]
        repo_lines.append(
            f"- **[{name}]({url})** ({stars}⭐, {language}, {forks} forks)\n"
            f"  {desc}\n  Topics: {topics_str}"
        )

    prompt = f"""Here are the top new GitHub repositories from the past 24 hours.
Write a 200-450 word engaging English summary explaining what each project does and why it matters, and end with a brief recommendation for developers.
No emojis.

Repositories:
{chr(10).join(repo_lines)}"""

    if not DEEPSEEK_API_KEY:
        return "LLM not configured. Set DEEPSEEK_API_KEY in .env."

    headers = {
        "Authorization": f"Bearer {DEEPSEEK_API_KEY}",
        "Content-Type": "application/json"
    }
    payload = {
        "model": "deepseek-chat",
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.7,
        "max_tokens": 600
    }

    try:
        resp = requests.post(
            f"{DEEPSEEK_BASE_URL}/chat/completions",
            headers=headers,
            json=payload,
            timeout=60
        )
        if resp.status_code == 200:
            return resp.json()["choices"][0]["message"]["content"]
        else:
            return f"LLM error: {resp.status_code}"
    except Exception as e:
        return f"LLM request failed: {e}"

async def update_trending_post():
    """替换旧的 trending 帖子为新生成的一篇"""
    from main import database, posts, get_current_time

    # 删除旧的 trending 帖子
    await database.execute(
        posts.delete().where(posts.c.title == "🤖 GitHub Trending Today")
    )

    repos = fetch_github_trending()
    summary = generate_trending_summary(repos)
    now = get_current_time()

    query = posts.insert().values(
        date=now,
        title="🤖 GitHub Trending Today",
        preview=summary,
        location="Auto-generated by DeepSeek",
        comment_count=0,
        likes_count=0,
        word_count=f"{len(summary)} chars"
    )
    await database.execute(query)

async def trending_scheduler():
    """每小时检查一次，到次日 0 点（北京时间）时更新"""
    while True:
        now = datetime.now(TZ_BEIJING)
        next_midnight = (now + timedelta(days=1)).replace(hour=0, minute=0, second=0, microsecond=0)
        wait_seconds = (next_midnight - now).total_seconds()
        await asyncio.sleep(wait_seconds)
        try:
            await update_trending_post()
        except Exception as e:
            print(f"Trending update failed: {e}")